### ISSUE TITLE
Excessive logging despite debug=false is set

### ISSUE THREAD

**Issue by AdiWehrli** [confluentinc/rest-utils#221]
Confluent schema-registry produces excessive number of log messages, if it wants to access a schema for a topic key/value which is not defined to have a schema, which should be ignored.

Example (real topic name replaced by a placeholder):
`
2021-02-04T05:51:16.226 level=ERROR logger=io.confluent.rest.exceptions.DebuggableExceptionMapper thread="qtp1105628551-27" msg="Request Failed with exception "
io.confluent.rest.exceptions.RestNotFoundException: Subject '{topicName}-key' not found.
        at io.confluent.kafka.schemaregistry.rest.exceptions.Errors.subjectNotFoundException(Errors.java:69)
        at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.validateAndGetSchema(KafkaSchemaRegistry.java:913)
        at io.confluent.kafka.schemaregistry.rest.resources.SubjectVersionsResource.getSchemaByVersion(SubjectVersionsResource.java:116)`

**Comment by AdiWehrli** [comment]
References #220
